Update demo app to use adwaita theme 0.0.4
gtk-flutter/libadwaita pull request #43
Opened 2022-01-03 23:48 UTC by pablojimpas

2022-01-04 15:14 UTC, MalcolmMielle commented on example/lib/flap/flap_demo.dart
> +          theme: adwaita.AdwaitaThemeData.light(),
With adwaita 0.0.4, there is no need for the namespace `adwaita`. Could you remove it :)?

2022-01-04 15:16 UTC, MalcolmMielle requested changes
Thanks for upgrading adwaita in the example :D!

I have a tiny tiny remark but otherwise, it's all good for me :)

PS: we're in the process of fixing the linter in #44 so don't worry about that.

2022-01-04 17:32 UTC, pablojimpas commented
> Thanks for upgrading adwaita in the example :D!
> 
> I have a tiny tiny remark but otherwise, it's all good for me :)
> 
> PS: we're in the process of fixing the linter in #44 so don't worry about that.

Perfect, I've just cleaned up that so I guess it's ready to be merged.

I ran `flutter analyze` in my local machine both on the root directory and the example directory and everything it's ok so I don't know what happened with GitHub Actions.

Keep up the great work, hopefully I can contribute more meaningful changes in the future!

2022-01-04 17:46 UTC, MalcolmMielle commented
Thanks for the PR and addressing the comments :).

I broke the GitHub actions, I'm new to it, hahahaa. Not your fault, hopefully it works now :D

2022-01-04 18:33 UTC, MalcolmMielle approved these changes

2022-01-04 19:28 UTC, merged

2022-01-05 17:07 UTC, MalcolmMielle requested changes
Just a comment about the drawer removal :).

LGTM otherwise.

Edit: this comment is for the wrong PR :S. Something happened in my VSCode haha