Updated to UniversalIO
gtk-flutter/libadwaita pull request #90
Opened 2024-03-12 03:16 UTC by NextdoorPsycho

This adds the Universal IO package, then updates your imports.
its the same thing, but it works on all platforms.
Cheers!

2024-03-28 17:18 UTC, prateekmedia requested changes

2024-03-28 17:18 UTC, prateekmedia commented on lib/src/widgets/adw/header_bar.dart
> +                            if (!widget.style.nativeControls || !kIsWeb && Platform.isLinux) SizedBox(width: widget.style.titlebarSpace),
Can you please format this file with line characters as 80, see this for more:
https://dart.dev/tools/linter-rules/lines_longer_than_80_chars

2024-03-28 17:18 UTC, prateekmedia commented on lib/src/widgets/adw/new/scaffold.dart
> +    @Deprecated('headerbar is deprecated, use the properties separately') AdwHeaderBar? Function(Widget?)? headerbar,
format this too again.

2024-03-28 17:19 UTC, prateekmedia commented
@NextdoorPsycho The PR looks good but the formatting is wrong, please format with respect to line limit 80 characters.

2024-03-28 20:41 UTC, NextdoorPsycho commented
You could literally just merge it and make a version bump on your IDE and
just visiting the page will make it auto format to 80.

On Thu, Mar 28, 2024 at 13:19 Prateek Sunal ***@***.***>
wrote:

> @NextdoorPsycho <https://github.com/NextdoorPsycho> The PR looks good but
> the formatting is wrong, please format with respect to line limit 80
> characters.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/gtk-flutter/libadwaita/pull/90#issuecomment-2025733743>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG7WI7A4553UR7KP77MJP43Y2RGLBAVCNFSM6AAAAABERNYY4SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDAMRVG4ZTGNZUGM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-11 20:18 UTC, prateekmedia approved these changes

2024-04-11 20:18 UTC, merged